name: '🐛 Bug'
description: 'Create-Better-Vite is not working as it should and needs to be fixed.'
assignees: ['QVGK']
labels: ['Bug']
title: '[BUG]: '
body:
  - type: dropdown
    id: 'related'
    attributes:
      label: 'What is this bug related to?'
      options:
        - Installer
        - React Template
        - Preact Template
        - Something Else
    validations:
      required: true

  - type: textarea
    id: 'what'
    attributes:
      label: 'What is happening?'
    validations:
      required: true

  - type: dropdown
    id: 'version'
    attributes:
      label: 'What version does this bug occur on?'
      options:
        - What I'm Reporting Doesn't Have a Version
        - V2.0.0-dev (Installer)
        - V1.6.2 (Installer)
        - V0.0.2 (Template)
    validations:
      required: true

  - type: dropdown
    id: 'when'
    attributes:
      label: 'When did this bug start to occur? (Rough Estimate)'
      options:
        - I Don't Know
        - Today
        - Yesterday
        - Sometime This Week
    validations:
      required: true
