name: '🐛 Bug'
description: 'QVGK Create-Vite is not working as it should and needs to be fixed.'
assignees: ['QVGK']
labels: ['Bug']
title: '[BUG]: '
body:
  - type: input
    id: 'what'
    attributes:
      label: 'What is happening?'
    validations:
      required: true
